### ISSUE TITLE
Proposal: class FrameLabels

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#15]
@JohannesAppel 

Displays every Frame with the same `frame.id` allways in the same `Label`.

```
class FrameLabels(tk.Frame):
    def __init__(self, parent, **kwargs):
        super().__init__(parent, bg='white', **kwargs)
        self.grid_columnconfigure(0, weight=1)
        
    def new_label(self):
        label = tk.Label(self, bg=self.cget('bg'), font=('Consolas', 10), anchor='nw', justify=tk.LEFT)
        label.grid(column=0, sticky='ew')
        return label
```
```
class App(tk.Tk):
    def __init__(self):
        ....
        self.received_frame = {}
        self.frame_labels = FrameLabels(self, width=280, height=100)
        self.frame_labels.pack()
        ...
```
```
    def display(self):
        if self.cbus.is_alive():
            frame = self.cbus.get()
            if frame is not None:
                # Do we have a Label for this frame.id
                label = self.received_frame.get(frame.id, None)
                
                # Unknown frame.id, assign a new Label
                if label is None:
                    label = self.frame_labels.new_label()
                    self.received_frame[frame.id] = label

                # Update the Label text
                label.configure(text="{:<5} {}".format(frame.id, self.cbus.text(frame.data)))
            else:
                self.none_count += 1

            self.after('idle', self.display)
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
There is a big space on top of the data that's being displayed in the `tkinter` window. What could be the problem for this?

I only disabled the previous `display()` function we had, And then added this new one from your comment.
![Screenshot (30)](https://user-images.githubusercontent.com/58848423/72044251-f9d54c00-32bb-11ea-8e1c-e63e380ecfc2.png)

**EDIT**
Nevermind, fixed the problem. Just disabled the following 2 lines
```
self.frame_listbox = FrameListbox(self, lines=self.cbus.cnt, height=0, width=0)
self.frame_listbox.pack()
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Just connected it to a bike. The output runs, but there is two problems:

- The output is extremely slow. I can hardly see if the data is updating or not. 
- (This problem we can fix when the output is working in real time.) I want to sort the outputted id's from low to high in the output.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>The output is extremely slow.

Sync with
https://github.com/JohannesAppel/johannesappel-/blob/aa135992bcce6237f6a6c0151da9183c6fce5647/DataLogger/src/canbus.py#L53
```
self.after(4, self.display)
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The 2 lines are already as you suggested now?

**Comment by WK-GiHu** [comment]
@JohannesAppel 

Show the stats data at `EXIT`.
Extend 
https://github.com/JohannesAppel/johannesappel-/blob/245edbe02436dad92837c42147b0c259f1611dff/DataLogger/src/main.py#L45

to

>Note: You have define `trashed_count` in `class CanBus`
```
print('EXIT, frame_count:{}, none_count:{}, trashed_count:{}'
    .format(self.cbus.frame_count, self.none_count, self.cbus.trashed_count)) 
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
The program doesn't allow me to close the `tkinter` window. It troughs out errors in the console.
```
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
CanBus.stop()
Trashed frames:23
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 45, in quit
    print('EXIT, frame_count:{}, none_count:{}, trashed_count:{}'.format(self.cbus.frame_count, self.none_count, self.cbus.trashed_count))
AttributeError: 'CanBus' object has no attribute 'trashed_count'
Received Frame ids:[268, 304, 660, 664, 680, 692, 700, 1016]
CanBus.stop()
Trashed frames:0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 44, in quit
    self.cbus.tearDownChannel()
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\canbus.py", line 72, in tearDownChannel
    self.ch.busOff()
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\site-packages\canlib\canlib\channel.py", line 363, in busOff
    dll.canBusOff(self.handle)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\site-packages\canlib\canlib\dll.py", line 103, in _error_check
    raise can_error(result)
canlib.canlib.exceptions.CanGeneralError: Handle is invalid (-10)
CanBus.stop()
Trashed frames:0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 44, in quit
    self.cbus.tearDownChannel()
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\canbus.py", line 72, in tearDownChannel
    self.ch.busOff()
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\site-packages\canlib\canlib\channel.py", line 363, in busOff
    dll.canBusOff(self.handle)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\site-packages\canlib\canlib\dll.py", line 103, in _error_check
    raise can_error(result)
canlib.canlib.exceptions.CanGeneralError: Handle is invalid (-10)
CanBus.stop()
Trashed frames:0
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 44, in quit
    self.cbus.tearDownChannel()
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\canbus.py", line 72, in tearDownChannel
    self.ch.busOff()
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\site-packages\canlib\canlib\channel.py", line 363, in busOff
    dll.canBusOff(self.handle)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\site-packages\canlib\canlib\dll.py", line 103, in _error_check
    raise can_error(result)
canlib.canlib.exceptions.CanGeneralError: Handle is invalid (-10)
```

And every time I try to press the exit button on the window, the same lines of errors are displayed. You can the see the errors that are repeating.

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>AttributeError: 'CanBus' object has no attribute 'trashed_count'

You didn't obey my Note: https://github.com/JohannesAppel/johannesappel-/issues/15#issuecomment-572734470

---

Insert after the Line 27
https://github.com/JohannesAppel/johannesappel-/blob/32da8dafe2f2b22a355651fdd3d895be4503d399/DataLogger/src/canbus.py#L27

```
    self.trashed_count = None
```

and before Line 41
https://github.com/JohannesAppel/johannesappel-/blob/32da8dafe2f2b22a355651fdd3d895be4503d399/DataLogger/src/canbus.py#L41

```
    self.trashed_count = self.queue.qsize()
```
disable Line 41
```
    # print('Trashed frames:{}'.format(...))
```

**Comment by JohannesAppel** [comment]
@WK-GiHu 
I don't know where the problem came in now, but the code isn't running anymore. It just went directly to `Canbus.stop()`.
```
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
CanBus.stop()
Received Frame ids:[]
```
