### ISSUE TITLE
main.py::App.display: AttributeError: 'str' object has no attribute 'id'

### ISSUE THREAD

**Issue by WK-GiHu** [JohannesAppel/johannesappel-#9]
And then there's a problem with the print function in the main. 
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Hex\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py", line 749, in callit
    func(*args)
  File "C:\Users\Hex\eclipse-workspace\DataLogger\src\main.py", line 34, in display
    self.text.insert(tk.END, "%s\t%s\n" %(frame.id, frame.data))
AttributeError: 'str' object has no attribute 'id'
```

_Originally posted by @JohannesAppel in https://github.com/JohannesAppel/johannesappel-/issues/8#issuecomment-567806510_

**Comment by WK-GiHu** [comment]
@JohannesAppel 

>AttributeError: 'str' object has no attribute 'id'

We have to verify this within `canbus.py`, the `Frame` object gets probably converted to `str` at `queue.put(...)`. Bad, i know nothing about `class Frame`.

Prepare `__main__` with:
```
    max_frames = 10
    for _ in range(max_frames):
        time.sleep(0.1)
        frame = cbus.get()
        if frame is None:
            none_count +=1
        else:
            print(type(frame))
        
    cbus.stop()
```

and show the output.

**Comment by JohannesAppel** [comment]
@WK-GiHu 
Here is the output:
```
canlib version: 8.30
Using channel: Kvaser Leaf Professional HS (channel 0), EAN: 73-30130-00404-7
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
<class 'canlib.frame.Frame'>
CanBus.stop()
EXIT, frame_count:394
```

**Comment by WK-GiHu** [comment]
@JohannesAppel 

The output is as expected, `<class 'canlib.frame.Frame'>` not `str`?

**Comment by WK-GiHu** [comment]
See https://github.com/JohannesAppel/johannesappel-/issues/13#issuecomment-572116098
